language: cpp

matrix:
    # Ubuntu 16.04 environment
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libeigen3-dev

script: 
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - ./runUnitTests